# Generated by Django 4.0.2 on 2022-03-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('March7App', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='JobType',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
